- name: Install desktop applications
  become: true
  package:
    name:
      - celluloid
      - copyq
      - flameshot
      - gimp-devel
      - keepassxc
      - libreoffice-fresh
      - remmina
      - telegram-desktop
      - thunar
      - wf-recorder
      - wireshark-qt
