- name: Install desktop applications
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --skipreview --mflags='-sr --noconfirm'
    name:
      - celluloid
      - copyq
      - flameshot
      - gimp-devel
      - keepassxc
      - libreoffice-fresh
      - remmina
      - telegram-desktop
      - thunar
      - wf-recorder
      - wireshark-qt
