- name: Install cursor packages
  become: true
  package:
    name:
      - sddm
      - bibata-cursor-theme
      - tela-circle-icon-theme-blue-git

- name: Install theme packages from aur
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --removemake --skipreview --mflags='-sr --noconfirm' --batchinstall
    name:
      - sddm-sugar-candy-git

- name: Create directory
  file:
    state: directory
    dest: "{{ item }}"
  with_items:
    - ~/.icons/default
    - ~/.config/gtk-3.0/
    - ~/.config/gtk-4.0/

- name: Copy icon configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: index.theme.template, dest: ~/.icons/default/index.theme }
    - { src: settings.ini.template, dest: ~/.config/gtk-3.0/settings.ini }
    - { src: settings.ini.template, dest: ~/.config/gtk-4.0/settings.ini }
    - { src: gtkrc-2.0.template, dest: ~/.gtkrc-2.0 }

- name: Apply icon theme for gtk applications
  shell: |
    gsettings set org.gnome.desktop.interface cursor-theme "{{ cursor }}"
    gsettings set org.gnome.desktop.interface icon-theme "{{ icons }}"
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface gtk-theme "{{ theme }}"

- name: Create sddm configuration directory
  become: true
  file:
    path: /etc/sddm.conf.d/
    state: directory

- name: Modify sddm configuration
  become: true
  community.general.ini_file:
    path: "/etc/sddm.conf.d/{{ item.section | lower }}.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_items:
    - { section: "General", option: "DisplayServer", value: "wayland" }
    - { section: "Theme", option: "Current", value: "sugar-candy" }
    - { section: "Theme", option: "CursorTheme", value: "{{ cursor }}" }
    - { section: "Theme", option: "CursorSize", value: "24" }

- name: Modify sddm theme configuration
  become: true
  replace:
    path: /usr/share/sddm/themes/sugar-candy/theme.conf
    regexp: "{{ item.pattern }}"
    replace: "{{ item.data }}"
  with_items:
    - data: 'Background="Backgrounds/Colorful Dune.jpg"'
      pattern: "^Background=.*$"
    - data: 'FormPosition="center"'
      pattern: "^FormPosition=.*$"
    - data: 'FullBlur="true"'
      pattern: "^FullBlur=.*$"
    - data: 'PartialBlur="false"'
      pattern: "^PartialBlur=.*$"

- name: Bring back minimize and maximize buttons in gtk
  shell: gsettings set org.gnome.desktop.wm.preferences button-layout "close,minimize,maximize:"

- name: Copy fonts to user directory
  ansible.posix.synchronize:
    src: "fonts/"
    dest: ~/.local/share/fonts/
    delete: yes
    recursive: yes

- name: update font cache
  shell: fc-cache
