- name: Install wayfire related packages
  become: true
  package:
    name:
      - arc-kde-git
      - kvantum
      - ffmpegthumbnailer
      - grim
      - kanshi
      - kitty
      - kvantum
      - network-manager-applet
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - qt5ct
      - qt5-graphicaleffects
      - qt5-quickcontrols2
      - qt5-svg
      - sddm
      - slurp
      - swayidle
      - swayimg
      - swaylock-effects
      - thunar
      - tumbler
      - weston
      - wf-recorder
      - wl-clipboard
      - wtype
      - zenity

- name: "deploy {{ item }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
  with_items:
    - wayfire
    - xdg-desktop-portal
    - wofi

- name: deploy wayfire binaries
  ansible.posix.synchronize:
    src: bin
    dest: ~/.local
    delete: yes
    recursive: yes

- name: deploy wayvnc
  ansible.posix.synchronize:
    src: wayvnc
    dest: ~/.config
    recursive: yes

- name: Create systemd directory
  file:
    state: directory
    path: ~/.config/systemd/user

- name: Search for the first drm card
  find:
    paths: /dev/dri/
    file_type: any
    recurse: no
    patterns: "card*"
  register: cards

- name: Create wayfire headless session service file
  template:
    src: wayfire-headless.service.template
    dest: ~/.config/systemd/user/wayfire-headless-session.service
  vars:
    drm_card: "{{ (cards.files | first)['path']  }}"

- name: Enable wayfire headless service
  systemd:
    name: wayfire-headless-session.service
    enabled: yes
    scope: user

- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "~/.config/Kvantum"
    - "~/.config/qt5ct"

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: qt5/kvantum.kvconfig, dest: ~/.config/Kvantum/kvantum.kvconfig }
    - { src: qt5/qt5ct.conf, dest: ~/.config/qt5ct/qt5ct.conf }
