- name: Install wayfire related packages
  become: true
  package:
    name:
      - arc-solid-gtk-theme
      - fcitx5
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-nord
      - fcitx5-qt
      - fcitx5-rime
      - ffmpegthumbnailer
      - grim
      - imagemagick
      - jq
      - kanshi
      - kitty
      - kvantum
      - kvantum-qt5
      - network-manager-applet
      - noto-fonts-emoji
      - pipewire-alsa
      - pipewire-audio
      - polkit-gnome
      - qt5ct
      - qt5-graphicaleffects
      - qt5-quickcontrols2
      - qt5-svg
      - qt6ct
      - sddm
      - slurp
      - spice-gtk
      - swayidle
      - swayimg
      - swaync
      - tumbler
      - udiskie
      - waybar
      - wayvnc
      - webp-pixbuf-loader
      - weston
      - wireplumber
      - wl-clipboard
      - wofi
      - wtype
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xorg-xwayland-lily
      - zenity

- name: Install packages which may be failed
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --removemake --skipreview --mflags='-sr --noconfirm' --batchinstall
    name:
      - arc-kde-git
      - cairo-dock-core-wayland-git
      - cairo-dock-plug-ins-wayland-git
      - wait-tray-ready-git
      - wlogout-git
      - siyuan-note-bin
  retries: 5
  delay: 10

- name: "deploy {{ item }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
    rsync_opts:
      - "--update"
  with_items:
    - fcitx5
    - fontconfig
    - kitty
    - swaync
    - waybar
    - wayfire
    - wayvnc
    - wlogout
    - wofi
    - xdg-desktop-portal

- name: Copy environment files to ~/.config/environment.d
  copy:
    src: "environment.d/{{ item }}"
    dest: "~/.config/environment.d/{{ item }}"
  with_items:
    - 60-fcitx.conf
    - 60-kitty.conf
    - 60-wayfire.conf
    - 60-wayland.conf
    - 61-de.conf

- name: deploy wayfire binaries
  ansible.posix.synchronize:
    src: bin
    dest: ~/.local
    delete: yes
    recursive: yes

- name: deploy cairo dock
  ansible.posix.synchronize:
    src: cairo-dock
    dest: ~/.config
    recursive: yes
    rsync_opts:
      - "--update"

- name: Create systemd directory
  file:
    state: directory
    path: ~/.config/systemd/user

- name: Search for the first drm card
  find:
    paths: /dev/dri/
    file_type: any
    recurse: no
    patterns: "card*"
  register: cards

- name: Create wayfire headless session service file
  template:
    src: wayfire-headless.service.template
    dest: ~/.config/systemd/user/wayfire-headless-session.service
  vars:
    drm_card: "{{ (cards.files | first)['path']  }}"

- name: Enable wayfire headless service
  systemd:
    name: wayfire-headless-session.service
    enabled: yes
    scope: user
