#!/bin/sh
/usr/bin/nvim \
    -u NONE \
    -c "let g:gruvbox_material_visual = 'reverse'" \
    -c "set ignorecase smartcase noruler termguicolors noshowcmd noshowmode nonumber nolist" \
    -c "set showtabline=0 foldcolumn=0 laststatus=0 clipboard=unnamedplus" \
    -c "let g:gruvbox_material_transparent_background=1" \
    -c "colorscheme gruvbox-material" \
    -c "autocmd TermOpen * normal G" \
    -c "map q :qa!<CR>" \
    -c "te bash -c 'echo -n \"\$(cat "$1" && sleep 0.3)\" && sleep 1000'"
