---
- hosts: desktop
  roles:
    - role: pacman
      tags: pacman
    - role: bootloader
      tags: bootloader
    - role: system
      tags: system
    - role: proxy
      tags: proxy
    - role: container
      tags: container
    - role: terminal
      tags: terminal
    - role: neovim
      tags: neovim
    - role: neomutt
      tags: neomutt
    - role: wayfire
      tags: wayfire
    - role: gnupg
      tags: gnupg
    - role: hidpi
      tags: hidpi
    - role: drop
      tags: drop
