set-option -g status on
set -g status-bg colour235
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
# set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-fg blue
set-option -g status-left "#(~/packages/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/packages/tmux-powerline/powerline.sh right)"
