- hosts: all
  strategy: free
  tasks:
    - name: Archlinux Upgrade
      become: true
      kewlfft.aur.aur:
        use: paru
        upgrade: true
        update_cache: true
        extra_args: --removemake --skipreview --mflags='-sr --noconfirm'
      become_user: aur_lotus
      when: ansible_distribution == "Archlinux"
    - name: Fedora Upgrade
      become: true
      dnf:
        name: '*'
        allowerasing: true
        state: latest
      when: ansible_distribution == "Fedora"
    - name: Update neovim
      shell: |
        nvim --headless -c "call dein#update()" +TSUpdateSync -c qa
        nvim --headless +CocUpdateSync -c qa
    - name: Update rust toolchain
      shell: |
        rustup update
      when: ansible_distribution == "Fedora"
