- name: Install proxy related packages
  become: true
  package:
    name:
      - clash-meta
      - yacd-meta
      - clash-geoip
      - frpc
      - gost

- name: Create clash service directory
  become: yes
  file:
    path: /etc/systemd/system/clash-meta.service.d
    state: directory

- name: Copy clash config
  become: true
  copy:
    src: ~/CloudBox/Sync/apps/clash/config.yaml
    dest: /etc/clash-meta/config.yaml
    owner: clash-meta
    group: clash-meta

- name: Copy clash override file
  become: yes
  copy:
    src: system/clash.conf
    dest: /etc/systemd/system/clash-meta.service.d/override.conf

- name: Copy proxy-routes service file
  become: yes
  copy:
    src: system/proxy-routes.service
    dest: /etc/systemd/system/proxy-routes.service

- name: Copy nftables initilize script
  become: yes
  copy:
    src: system/bin/nftproxy.sh
    dest: /usr/local/sbin/nftproxy.sh
    mode: 0755

- name: "Get current systemd default"
  become: yes
  command: "systemctl get-default"
  changed_when: false
  register: systemdefault

- name: "Set default to multi-user target"
  become: yes
  command: "systemctl set-default multi-user.target"
  when: "'multi-user' not in systemdefault.stdout"

- name: Restart clash
  become: yes
  ansible.builtin.systemd:
    daemon_reload: true
    name: clash-meta
    enabled: yes
    state: restarted

- name: Start frpc
  become: yes
  ansible.builtin.systemd:
    daemon_reload: true
    name: frpc
    enabled: yes
    state: restarted

- name: Start transparent proxy
  become: yes
  ansible.builtin.systemd:
    daemon_reload: true
    name: proxy-routes
    enabled: yes
    state: started
