#=============================================================================
# init.toml --- SpaceVim config
# Copyright (c) 2018 RedLotus
# Author: RedLotus < ssfdust@gmail.com >
#=============================================================================

# SpaceVim options {{{
[options]
    default_indent = 4
    plugin_manager_processes = 16
    filemanager = 'defx'
    plugin_manager_max_processes = 16
    buffer_index_type = 1
    enable_debug = 1
    lint_on_the_fly = 1
    enable_ale = 0
    update_retry_cnt = 3
    enable_vimfiler_filetypeicon = 1
    enable_vimfiler_welcome = 0
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = 1
    enable_os_fileformat_icon = 1
    statusline_separator = 'slant'
    github_username = 'ssfdust'
    auto_disable_touchpad = 0
    colorscheme = 'onedark'
    enable_tabline_filetype_icon = true
    bootstrap_before = "custom#before"
    bootstrap_after = "custom#after"
    project_rooter_automatically = 1
# disabled_plugins = ["denite.nvim"]

# }}}

# # SpaceVim layer config {{{
[[layers]]
    name = 'denite'
[[layers]]
    name = 'checkers'
    show_cursor_error = true
[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = "lsp"
    filetypes = [
        "python",
        "vue",
        "javascript"
    ]
    [layers.override_cmd]
    vue = ['vls', '--stdio']
    python = ['pyls', '--log-file', '/tmp/pyls.log', '-vvv']
    javascript = ['vls', '--stdio']
[[layers]]
    name = "debug"
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'lang#toml'
[[layers]]
    name = 'lang#sql'
[[layers]]
    name = 'lang#python'
[[layers]]
    name = 'lang#vim'
[[layers]]
    name = 'lang#json'
[[layers]]
    name = 'lang#vue'
[[layers]]
    name = 'lang#markdown'
    enableWcwidth = 1
    listItemIndent = 1
[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30
# # }}}


[[custom_plugins]]
    name = 'antoyo/vim-licenses'
    merged = 0
[[custom_plugins]]
    name = 'tpope/vim-obsession'
    merged = 0
[[custom_plugins]]
    name = 'gisphm/vim-gitignore'
    merged = 0
[[custom_plugins]]
    name = 'alfredodeza/pytest.vim'
    merged = 0
[[custom_plugins]]
    name = 'pseewald/vim-anyfold'
    merged = 0
# [[custom_plugins]]
    # name = "SpaceVim/denite.nvim"
    # merged = false
    # loadconf = true

