- name: Install xsettingsd
  become: true
  package:
    name:
      - xsettingsd
      - xorg-xrdb

- name: Enable xsettingsd service
  systemd:
    daemon_reload: false
    name: xsettingsd
    enabled: yes
    state: started
    scope: user

- name: Create files if they don't exist
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - "~/.Xresources"
    - "~/.xsettingsd"
    - "~/.config/environment.d/62-hidpi.conf"

- name: modify xsettingsd configuration
  lineinfile:
    path: ~/.xsettingsd
    line: "{{ item }}"
    state: present
  with_items:
    - '"Xft/DPI" 196'
    - '"Gdk/UnscaledDPI" 98304'
    - '"Gdk/WindowScalingFactor 2"'
    - '"Gtk/CursorThemeSize" 48'
    - '"Xcursor/size" 48'

- name: Check if Xft.dpi configuration exists in .Xresources file
  shell: grep -q '^Xft.dpi' ~/.Xresources
  register: dpi_check
  changed_when: false
  ignore_errors: true

- name: Create hidpi.conf for qt support
  lineinfile:
    path: ~/.config/environment.d/62-hidpi.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "QT_AUTO_SCREEN_SCALE_FACTOR=1"
    - "QT_ENABLE_HIGHDPI_SCALING=1"

- name: Add or modify Xft.dpi configuration
  lineinfile:
    path: ~/.Xresources
    line: "{{ item }}"
    state: present
  when: dpi_check.rc != 0
  with_items:
    - "! Set Xft.dpi to control the DPI"
    - "Xft.dpi: 192"

- name: Modify the value of Xft.dpi configuration
  lineinfile:
    path: ~/.Xresources
    regexp: '^Xft.dpi:'
    line: 'Xft.dpi: 192'
  when: dpi_check.rc == 0

- name: Add xwayland autostart configuration to wayfire.ini
  blockinfile:
    path: ~/.config/wayfire/wayfire.ini
    marker: "# {mark} ANSIBLE BLOCK"
    insertafter: '^\[autostart\]'
    block: |
      xrdb = xrdb -load ~/.Xresources \
          && xprop -root \
              -format _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c \
              -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2

- name: Modify hidpi for plymouth
  become: true
  community.general.ini_file:
    path: /etc/plymouth/plymouthd.conf
    section: Daemon
    option: DeviceScale
    value: 2

- name: Update cursor size to hidpi
  shell: gsettings set org.gnome.desktop.interface cursor-size 24

- name: Modify sddm configuration
  become: true
  community.general.ini_file:
    path: "/etc/sddm.conf.d/{{ item.section | lower }}.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_items:
    - { section: "Theme", option: "CursorSize", value: "48" }
    - section: "General"
      option: "GreeterEnvironment"
      value: "QT_SCREEN_SCALE_FACTORS=2,QT_FONT_DPI=192"
