- name: Remove iptables
  become: true
  package:
    name:
      - iptables
    state: absent
    force: true

- name: Install base system packages
  become: true
  package:
    name:
      - bind
      - cockpit
      - cockpit-machines
      - cockpit-podman
      - cockpit-storaged
      - dmidecode
      - firewalld
      - gnu-netcat
      - go
      - gptfdisk
      - iptables-nft
      - libva-mesa-driver
      - linux-firmware
      - man-db
      - mesa-vdpau
      - net-tools
      - networkmanager
      - nfs-utils
      - nftables
      - openssh
      - plocate
      - python-pyqt5
      - reflector
      - rust
      - syncthing
      - usb_modeswitch
      - usbutils
      - ventoy-bin
      - wireless_tools

- name: Write hostname to /etc/hostname
  become: true
  copy:
    content: "{{ hostname }}"
    dest: /etc/hostname

- name: Update system locale
  become: true
  shell: |
    sed -i.bak \
        -e 's/#[ ]*\(en_US\)/\1/' \
        -e 's/#[ ]*\(zh_CN\)/\1/' \
        /etc/locale.gen
    locale-gen

- name: Create locale configuration
  become: true
  copy:
    content: "LANG=en_US.UTF-8"
    dest: /etc/locale.conf

- name: Set system timezone
  become: true
  shell: |
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

- name: Enable system services
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
  with_items:
    - NetworkManager
    - sddm-plymouth
    - firewalld
    - libvirtd
    - plocate-updatedb.timer
    - nfsv4-server
  ignore_errors: true

- name: Check zfs module
  shell: lsmod | grep -q zfs
  ignore_errors: true
  register: zfs_chk

- name: Disable system resolved services
  become: true
  systemd:
    name: "systemd-resolved"
    enabled: false
    state: "stopped"

- name: Update modules in mkinitcpio.conf
  become: true
  replace:
    path: /etc/mkinitcpio.conf
    regexp: "^MODULES=.*$"
    replace: "MODULES=(i915{{ ' spl zfs' if zfs_chk.rc == 0 else '' }})"

- name: Update hooks in mkinitcpio.conf
  become: true
  replace:
    path: /etc/mkinitcpio.conf
    regexp: "^HOOKS=.*$"
    replace: "HOOKS=(base systemd sd-plymouth modconf block keyboard{{ ' sd-zfs' if zfs_chk.rc == 0 else '' }} filesystems)"
  register: hooks_update

- name: Regenerate initramfs
  become: true
  shell: mkinitcpio -P
  when: hooks_update.changed

- name: Ensure user systemd configuration directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: initialize git lfs
  shell: git lfs install

- import_tasks: cockpit.yml
