- name: Install podman packages
  become: true
  package:
    name:
      - aardvark-dns
      - buildah
      - podman
      - podman-compose
      - skopeo
- name: Get hostname
  set_fact:
    cockpit_host: "cockpit.{{ ansible_facts['nodename'] | lower }}.me"
- name: Search for shortnames configuration
  find:
    paths: /etc/containers/registries.conf.d
    file_type: file
    recurse: no
    patterns: "*shortnames*"
  register: shortnames
- name: Switch to nju repo
  become: true
  replace:
    path: "{{ item.path }}"
    regexp: "{{ item.orig }}"
    replace: "{{ item.new }}"
  with_items:
    - { orig: 'docker.nju.edu.cn', new: 'docker.io', path: "{{ shortnames.files[0].path }}" }
    - { orig: 'quay.nju.edu.cn', new: 'quay.io', path: "{{ shortnames.files[0].path }}" }
    - { orig: "{{ registries_match }}", new: "{{ new_registries }}", path: "/etc/containers/registries.conf" }
  vars:
    registries_match: '^[#]*\s*unqualified-search-registries.*$'
    new_registries: 'unqualified-search-registries = ["docker.io"]'
- name: Enable podman services
  become: true
  systemd:
    daemon_reload: true
    name: "{{ item }}"
    enabled: yes
  with_items:
    - "podman-restart"
    - podman
- name: "Set subuid and subgid for {{ ansible_user_id }}"
  become: true
  shell: |
    usermod --add-subuids 100000-165535 --add-subgids 100000-165535 {{ ansible_user_id }}
- import_tasks: cockpit.yml
- import_tasks: waydroid.yml
