- name: Install waydroid related packages
  become: true
  package:
    name:
      - waydroid
      - lzip
      - python-pyclip
      - binder_linux-dkms

- name: Install packages from aur
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --removemake --skipreview --mflags='-sr --noconfirm' --batchinstall
    name:
      - python-inquirerpy

- name: Init waydroid
  become: true
  shell: |
    modprobe binder_linux || true

- name: Write waydroid module to modules-load.d of systemd
  become: true
  copy:
    content: "binder_linux"
    dest: /etc/modules-load.d/binder_linux.conf

- name: Clone waydroid_script to /usr/local/share
  become: true
  git:
    repo: https://github.com/casualsnek/waydroid_script
    dest: /usr/local/share/waydroid_script
