- name: Look for refind directory
  find:
    paths: /boot
    recurse: yes
    file_type: directory
    patterns: refind
  register: ret

- name: Copy refind configuration
  become: yes
  copy:
    src: refind.conf
    dest: "{{ ret.files[0].path }}/refind.conf"
