- name: Copy pacman configurations
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: pacman.conf, dest: /etc/pacman.conf }
    - { src: makepkg.conf, dest: /etc/makepkg.conf }
    - { src: xyne-mirrorlist, dest: /etc/pacman.d/xyne-mirrorlist }
