- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_lotus
    create_home: yes
    group: users

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_lotus ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install base archlinux package manager dependancies
  become: true
  package:
    update_cache: true
    name:
      - aria2
      - git-lfs

- name: Copy pacman configurations
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: pacman.conf, dest: /etc/pacman.conf }
    - { src: makepkg.conf, dest: /etc/makepkg.conf }
    - { src: pacman-aria2.conf, dest: /etc/pacman.d/pacman-aria2.conf }
    - { src: xyne-mirrorlist, dest: /etc/pacman.d/xyne-mirrorlist }

- name: refresh keyrings
  become: true
  shell: |
    pacman-key --lsign-key "farseerfc@archlinux.org"

- name: Install base archlinux keyring
  become: true
  package:
    update_cache: true
    name:
      - archlinuxcn-keyring

- name: Install base archlinux package manager
  become: true
  package:
    name:
      - pacman-contrib
      - paru
      - pkgfile

- name: Configure auto clean for paru
  become: true
  lineinfile:
    path: /etc/paru.conf
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
  with_items:
    - reg: '^#.*RemoveMake$'
      line: RemoveMake
    - reg: '^#.*CleanAfter$'
      line: CleanAfter
