- stat:
    path: "~/.config/neomutt"
  register: link

- name: remove symlink
  file:
    path: "~/.config/neomutt"
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: Create directories for notmuch
  file:
    path: "~/.local/share/mail/{{ item }}"
  with_items:
    - "gmail"
    - "qq"
    - "juminfo"

- name: Create notmuch config
  template:
    src: notmuch-config.template
    dest: ~/.notmuch-config

- name: deploy neomutt
  ansible.posix.synchronize:
    src: neomutt
    dest: ~/.config
    delete: no
    recursive: yes

- name: Initlize mail sync service
  copy:
    src: "{{ item }}"
    dest: ~/.config/systemd/user
  with_fileglob:
    - "services/*"

- name: Enable mail sync service
  systemd:
    daemon_reload: false
    name: mail.timer
    enabled: yes
    scope: user
