- name: Install terminal related packages
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --skipreview --mflags='-sr --noconfirm'
    name:
      - isync
      - lieer-git
      - msmtp
      - neomutt
      - notmuch
      - notmuch-addrlookup-c
      - pandoc-bin

- name: "deploy {{ item }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
  with_items:
    - neomutt
    - msmtp
    - mbsync

- name: Copy accounts to neomutt
  ansible.posix.synchronize:
    src: "~/CloudBox/Sync/accounts"
    dest: ~/.config/neomutt
    delete: yes
    recursive: yes

- name: Create directories for notmuch
  file:
    path: "~/.local/share/mail/{{ item }}"
    state: "directory"
  with_items:
    - "gmail"
    - "qq"
    - "juminfo"

- name: Create notmuch config
  template:
    src: notmuch-config.template
    dest: ~/.notmuch-config

- name: Check if notmuch is needed to be initilized
  stat:
    path: ~/.local/share/mail/.notmuch
  register: notmuch_db

- name: Initlize notmuch
  shell: notmuch new
  when: not notmuch_db.stat.exists

- name: Initlize mail sync service
  copy:
    src: "{{ item }}"
    dest: ~/.config/systemd/user
  with_fileglob:
    - "services/*"

- name: Enable mail sync service
  systemd:
    daemon_reload: false
    name: mail.timer
    enabled: yes
    scope: user
