- name: Drop some packages
  become: true
  package:
    name:
      - pulseaudio
      - caddy
      - wf-shell-git
      - wcm-git
    state: absent

- name: Drop sddm wayland configuration
  become: true
  file:
    path: /etc/sddm.conf.d/wayland.conf
    state: absent
