- name: Install waybar package
  become: true
  package:
    name:
      - waybar
      - swaync
      - udiskie
      - jq

- name: "deploy {{ item }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
  with_items:
    - waybar
    - swaync
