- name: Install terminal related packages
  become: true
  package:
    name:
      - bpftrace
      - fastfetch
      - fd
      - fzf
      - gdb
      - htop
      - lf
      - lshw
      - lsof
      - mycli
      - nmap
      - nushell
      - p7zip
      - pass
      - plocate
      - pueue
      - pwru
      - python-pexpect
      - ripgrep
      - rsync
      - rye
      - sshfs
      - starship
      - strace
      - tcpdump
      - trash-cli
      - unarchiver
      - unzip
      - wget
      - yarn
      - zellij
      - zoxide

- name: Install terminal related packages from aur
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --removemake --skipreview --mflags='-sr --noconfirm' --batchinstall
    name:
      - archivemount
      - carapace-bin
      - neovim-gruvbox-material-git

- name: "deploy {{ item }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
  with_items:
    - lf
    - mycli
    - nushell
    - password-store
    - pueue
    - starship
    - zellij

- name: Ensure ~/.config/environment.d directory exists
  file:
    path: ~/.config/environment.d
    state: directory

- name: Initilize rye
  expect:
    command: rye
    timeout: 10800
    responses:
      "y/n": y
  args:
    creates: ~/.rye 
  register: rye_stat

- name: Install weathercn package
  shell: ~/.rye/shims/rye install py-weathercn
  when: rye_stat.changed

- name: Copy environment files to ~/.config/environment.d
  copy:
    src: "environment.d/{{ item }}"
    dest: "~/.config/environment.d/{{ item }}"
  with_items:
    - 11-ssh-agent.conf
    - 60-shell.conf
    - 61-lf.conf
    - 61-pass.conf

- name: Create gdb configuration directory
  file:
    path: ~/.config/gdb
    state: directory

- name: Update gdbinit
  get_url:
    url: https://raw.githubusercontent.com/gdbinit/Gdbinit/master/gdbinit
    dest: ~/.config/gdb/gdbinit 

- name: deploy "{{ item.src }}"
  copy:
    src: "{{ item. src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: profile
      dest: ~/.bash_profile
    - src: gitconfig
      dest: ~/.gitconfig

- name: Create zpager executable file
  become: true
  copy:
    src: zpager
    dest: /usr/local/bin/zpager
    mode: 0o755

- name: Create ssh configuration directory
  file:
    path: ~/.ssh
    state: directory
    mode: '700'

- name: Insert git ssh block
  blockinfile:
    create: true
    path: ~/.ssh/config
    marker: "# {mark} ANSIBLE BLOCK"
    insertbefore: 'BOF'
    append_newline: true
    block: |
      Host github.com
          HostName ssh.github.com
          User git
          Port 443
          PreferredAuthentications publickey

      Host gitlab.com
          Hostname altssh.gitlab.com
          User git
          Port 443
          PreferredAuthentications publickey

      Host *
        HostKeyAlgorithms=+ssh-rsa

- name: Ensure ssh configuration permission
  file:
    path: ~/.ssh/config
    state: file
    mode: '600'

- name: Enable pueued service
  systemd:
    name: pueued
    enabled: yes
    scope: user
  ignore_errors: true
