- name: Install terminal related packages
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --skipreview --mflags='-sr --noconfirm'
    name:
      - archivemount
      - carapace-bin
      - fastfetch
      - fd
      - fzf
      - htop
      - lf
      - lsof
      - mycli
      - neovim-gruvbox-material-git
      - nmap
      - nushell
      - p7zip
      - pass
      - plocate
      - ripgrep
      - rsync
      - rye
      - sshfs
      - strace
      - starship
      - tcpdump
      - trash-cli
      - unarchiver
      - unzip
      - wget
      - yarn
      - zellij
      - zoxide

- name: "deploy {{ item }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
  with_items:
    - lf
    - mycli
    - nushell
    - password-store
    - pueue
    - starship
    - zellij

- name: Ensure ~/.config/environment.d directory exists
  file:
    path: ~/.config/environment.d
    state: directory

- name: Copy environment files to ~/.config/environment.d
  copy:
    src: "environment.d/{{ item }}"
    dest: "~/.config/environment.d/{{ item }}"
  with_items:
    - 11-ssh-agent.conf
    - 60-shell.conf
    - 61-lf.conf
    - 61-pass.conf

- name: Create gdb configuration directory
  file:
    path: ~/.config/gdb
    state: directory

- name: Update gdbinit
  uri:
    url: https://raw.githubusercontent.com/gdbinit/Gdbinit/master/gdbinit
    dest: ~/.config/gdb/gdbinit 

- name: deploy profile
  copy:
    src: profile
    dest: ~/.bash_profile

- name: Create zpager executable file
  become: true
  copy:
    src: zpager
    dest: /usr/local/bin/zpager
    mode: 0o755

- name: Create ssh configuration directory
  file:
    path: ~/.ssh
    state: directory
    mode: '700'

- name: Ensure ssh configuration permission
  file:
    path: ~/.ssh/config
    state: file
    mode: '600'

- name: Insert git ssh block
  blockinfile:
    path: ~/.ssh/config
    marker: "# {mark} ANSIBLE BLOCK"
    insertbefore: 'BOF'
    block: |
      Host github.com
          HostName ssh.github.com
          User git
          Port 443
          PreferredAuthentications publickey

      Host gitlab.com
          Hostname altssh.gitlab.com
          User git
          Port 443
          PreferredAuthentications publickey

      Host *
        HostKeyAlgorithms=+ssh-rsa
