- name: Install virtualization related packages
  become: true
  package:
    name:
      - dnsmasq
      - guestfs-tools
      - libvirt
      - virglrenderer
      - virt-install
      - virt-viewer
      - qemu-base
      - qemu-hw-usb-host
      - vagrant

- name: Install virtualbox packages
  become: true
  package:
    name:
      - virtualbox-host-dkms
      - virtualbox

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: true

- name: Check whether libvirt plugin is installed
  shell: |
    vagrant plugin list
  register: vagrant_plugins

- name: Install libvirt plugin
  shell: |
    vagrant plugin install vagrant-libvirt
  when: '"vagrant-libvirt" not in vagrant_plugins.stdout'

- name: Create vagrant-trusted network
  become: true
  copy:
    src: vagrant-trusted.xml
    dest: /etc/libvirt/qemu/networks/vagrant-trusted.xml
    mode: '600'
