require('dein_init')
require('core/options')
require('core/autocmds')
require('core/keymaps')
require('core/colors')
require('plugins/alpha')
require('plugins/airline')
require('plugins/ddu')
require('plugins/treesitter')
require('plugins/coc')
require('plugins/leetcode')
require('plugins/deol')
require('plugins/licenses')
require('plugins/rooter')
-- require('plugins/chatgpt')
