- name: Enable nessary sevices
  become: true
  ansible.posix.firewalld:
    service: "{{ item.service }}"
    zone: "{{ item.zone }}"
    permanent: true
    state: enabled
  with_items:
    - service: http
      zone: public
    - service: https
      zone: public
    - service: nfs
      zone: public
    - service: vnc-server
      zone: public
    - service: syncthing
      zone: public
    - service: dns
      zone: public
- name: Enable ports
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "6888/tcp"
    - "7890/tcp"
    - "6888/udp"
    - "29418/tcp"
- name: Add trusted interface
  become: true
  ansible.posix.firewalld:
    zone: trusted
    interface: waydroid0
    permanent: true
    state: enabled
