- name: Install bootloader related packages
  become: true
  package:
    name:
      - refind
      - plymouth-git
      - plymouth-theme-arch-charge-big

- name: Install refind bootloader to bios
  become: true
  shell: refind-install

- name: Install bootloader theme
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --removemake --skipreview --mflags='-sr --noconfirm'
    name:
      - refind-theme-darkmini-git

- name: Set plymouth theme
  become: true
  shell: |
    grep -q arch-charge-big /etc/plymouth/plymouthd.conf \
      || plymouth-set-default-theme -R arch-charge-big

- name: Look for refind directory
  find:
    paths: /boot
    recurse: yes
    file_type: directory
    patterns: refind
  register: ret

- name: get root boot parition
  register: root_part
  shell: |
    awk '
    {
        if ($2 == "/") {
            if ($1 ~ "zroot") {
                printf("ZFS=%s", $1)
            } else if ($1 ~ "/dev/mapper/") {
                print $1
            } else if ($1 ~ "/dev/") {
                diskname = substr($1, 6, length($1) - 5)
                cmd = "ls /dev/disk/by-uuid/"
                while ( cmd | getline uuid ) {
                    "readlink -f /dev/disk/by-uuid/" uuid | getline disk
                    if (disk == $1) {
                        printf("UUID=%s", uuid)
                    }
                }
            }
        }
    }
    ' /proc/mounts

- name: Check if lts kernel exists
  find:
    pattern: '*linux-lts*'
    path: /boot
  register: search_lts

- name: Copy refind configuration
  become: true
  template:
    src: refind.conf.j2
    dest: "{{ ret.files[0].path }}/refind.conf"
  vars:
    boot_part: "{{ root_part.stdout }}"
    linux_lts: "{{ search_lts.matched > 0 }}"
