- name: Install bootloader related packages
  become: true
  become_user: aur_lotus
  kewlfft.aur.aur:
    use: paru
    extra_args: --skipreview --mflags='-sr --noconfirm'
    name:
      - refind
      - plymouth-git
      - plymouth-theme-arch-charge-big
      - refind-theme-darkmini-git

- name: Install refind bootloader to bios
  become: true
  shell: refind-install

- name: Set plymouth theme
  become: true
  shell: plymouth-set-default-theme -R arch-charge-big

- name: Look for refind directory
  find:
    paths: /boot
    recurse: yes
    file_type: directory
    patterns: refind
  register: ret

- name: Copy refind configuration
  become: true
  copy:
    src: refind.conf
    dest: "{{ ret.files[0].path }}/refind.conf"
