set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# Switch to 'wfx/tmux-power'
# set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'ssfdust/tmux-power'
set -g @plugin 'ssfdust/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# set prefix
set -g prefix C-a
set -g mouse on

unbind-key C-b
bind-key C-a send-prefix
set-window-option -g aggressive-resize

# enable vi mode
set-window-option -g mode-keys vi 

# enable 256 color support
set -g default-terminal "xterm-256color"
set -g terminal-overrides ',xterm-256color:Tc'
set -g status-bg colour235

setw -g automatic-rename off
setw -g allow-rename off
# restore neovim
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-save-command-strategy 'linux_procfs'
set -g @resurrect-processes 'telegram-cli mosh-client ett neomutt w3m'

set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 90
set-option -g status-right-length 100
# set-window-option -g window-status-current-bg black
# set-window-option -g window-status-current-fg blue
set-option -gq "@resurrect-hook-post-save-layout" "/home/ssfdust/.tmux/plugins/tmux-resurrect-virtualenvwrapper/bin/tmux-virtualenv.sh save"
set-option -gq "@resurrect-hook-pre-restore-history" "/home/ssfdust/.tmux/plugins/tmux-resurrect-virtualenvwrapper/bin/tmux-virtualenv.sh restore"
set -g window-status-current-format '#[fg=blue]#I:#W '

# Disabled tmux-powerline configuration
# set-option -g status-left "#(~/.tmux/plugins/tmux-powerline/powerline.sh left)"                                               
# set-option -g status-right "#(~/.tmux/plugins/tmux-powerline/powerline.sh right)"                                             

# Set up tmux power theme
set -g @tmux_power_show_upload_speed true
set -g @tmux_power_show_download_speed true
set -g @tmux_power_theme 'coral'
set -g @tmux_power_show_mailcount true
set -g @tmux_power_show_ip true
set -g @tmux_power_show_weather true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)                                             

run '~/.tmux/plugins/tpm/tpm'
