set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# set prefix
set prefix C-a

unbind-key C-b
bind-key C-a send-prefix

# enable 256 color support
set -g default-terminal "xterm-256color"
set -g terminal-overrides ',xterm-256color:Tc'
set -g status-bg colour235

setw -g automatic-rename off
setw -g allow-rename off
# restore neovim
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'ipython ssh psql mysql sqlite3'

set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 90
set-option -g status-right-length 100
# set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-fg blue
set-option -g status-left "#(~/.tmux/plugins/tmux-powerline/powerline.sh left)"                                               
set-option -g status-right "#(~/.tmux/plugins/tmux-powerline/powerline.sh right)"                                             
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)                                             

run '~/.tmux/plugins/tpm/tpm'
