# P9K MUST BE AT THE VERY FIRST
P9K_MODE='nerdfont-complete'
P9K_DIR_SHORTEN_LENGTH=2

## Prompt Variable
P9K_PROMPT_ON_NEWLINE=false
P9K_PROMPT_ADD_NEWLINE=false
P9K_RPROMPT_ON_NEWLINE=true
## VCS Variable
P9K_VCS_SHOW_CHANGESET=false
P9K_VCS_CHANGESET_HASH_LENGTH=6
## Other Variable
P9K_TIME_FORMAT="%F %T"
P9K_STATUS_VERBOSE=false

## Customizing Prompt Segments
P9K_LEFT_PROMPT_ELEMENTS=(os_icon context disk_usage dir_writable newline dir vcs)
P9K_RIGHT_PROMPT_ELEMENTS=(status anaconda vi_mode virtualenv)
P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON="\n"

# Path to your oh-my-zsh configuration.
ZSH=~/.oh-my-zsh/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export TERM="xterm-256color"
if [[ $(tty) == \/dev\/tty[0-9]* ]]; then
	ZSH_THEME="duellj"
elif [[ $TERM == "xterm-256color" || $TERM == "screen-256color" ]]; then
	ZSH_THEME="powerlevel10k/powerlevel10k"
else
	ZSH_THEME="dst"
fi

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# tmux autostart
ZSH_TMUX_AUTOSTART="false"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="false"

# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=3

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
ENABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(vi-mode
         systemd
         colorize
         zsh_reload
         cp
         archlinux
         docker
         python
         common-aliases
         arch_update
         history-substring-search
         history
         git
         themes
         github
         tmux
         golang
         rust
         thefuck
         arch_update
         zsh_reload
         zsh-completions
         zsh-autosuggestions
         zsh-syntax-highlighting
         pipenv
         virtualenv)

source $ZSH/oh-my-zsh.sh

# User configuration

export GOPATH="$HOME/Programming/development/go"
export CARGO_HOME="$HOME/Programming/packages/cargo"
export RUST_HOME="$HOME/Programming/packages/rust"
export PATH=$HOME/.bin:$HOME/.rvm/bin:$GOPATH/bin:$CARGO_HOME/bin:/usr/local/bin:$PATH
export PYTHON_HOST_PROG='/usr/bin/python2'
export PYTHON3_HOST_PROG='/usr/bin/python3'

remoteip=45.76.106.238

# Prefer vi-mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Custom alias command
alias pipurl="sed -i \"s/org/doubanio.com/\" Pipfile "
alias switch_ap="sudo systemctl stop create_ap_1 && sudo systemctl start create_ap"
alias nvr="nvr --remote-tab"
alias dzps="fuck"
alias neofetch="neofetch --ascii_colors 33 33"
alias ls="exa"

# # Preferred editor for local and remote sessions
#if [[ -n $SSH_CONNECTION ]]; then
#  export EDITOR='vim'
#else
#  export EDITOR='mvim'
#fi
export EDITOR='nvim'
# Compilation flags
# export ARCHFLAGS="-arch x86_64"
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin:$HOME/.poetry/bin:$HOME/.yarn/bin:$HOME/.local/bin/"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
