# Path to your oh-my-zsh configuration.
ZSH=~/.oh-my-zsh/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export TERM="xterm-256color"
if [[ $(tty) == \/dev\/tty[0-9]* ]]; then
	ZSH_THEME="duellj"
fi
# elif [[ $TERM == "xterm-256color" || $TERM == "screen-256color" ]]; then
#     ZSH_THEME="powerlevel10k/powerlevel10k"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# tmux autostart
ZSH_TMUX_AUTOSTART="false"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="false"

# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=3

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
ENABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(vi-mode
         systemd
         colorize
         zsh_reload
         scd
         cp
         archlinux
         docker
         python
         common-aliases
         vgl
         arch_update
         history-substring-search
         history
         git
         themes
         github
         tmux
         golang
         rust
         thefuck
         arch_update
         zsh_reload
         zsh-completions
         zsh-autosuggestions
         zsh-syntax-highlighting
         pipenv
         podman
         virtualenv
         pyenv
         invoke)

source $ZSH/oh-my-zsh.sh

# User configuration

export SUDO_ASKPASS="$HOME/dotfiles/bin/askpass"
export GOPATH="$HOME/Programming/development/go"
export CARGO_HOME="$HOME/Programming/packages/cargo"
export RUST_HOME="$HOME/Programming/packages/rust"
export PYTHON_HOST_PROG='/usr/bin/python2'
export PYTHON3_HOST_PROG='/usr/bin/python3'
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
export GPG_TTY=$(tty)
export STARSHIP_CONFIG=~/.config/starship/starship.toml
export EDITOR='nvim'
export GTAGSLABEL=pygments
# add pyenv to path
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$HOME/.poetry/bin:$HOME/.yarn/bin:$HOME/.local/bin:$HOME/dotfiles/bin:$PATH"

# Prefer vi-mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Custom alias command
alias switch_ap="sudo systemctl stop create_ap_1 && sudo systemctl start create_ap"
alias nvr="nvr --remote-tab"
alias dzps="fuck"
alias neofetch="neofetch --ascii_colors 33 33"
alias ls="exa"
alias la="ls -al"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

if [[ "$(is_vgl_enabled)" = "enabled" ]];then
    export LD_PRELOAD=/usr/lib64/libdlfaker.so:/usr/lib64/libvglfaker.so
fi

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
if command -v starship 1>/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
