- stat:
    path: "~/.config/starship"
  register: link

- name: remove symlink
  file:
    path: "~/.config/starship"
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: deploy starship
  ansible.posix.synchronize:
    src: starship
    dest: ~/.config
    delete: yes
    recursive: yes
