- stat:
    path: "~/.config/mbsync"
  register: link

- name: remove symlink
  file:
    path: "~/.config/mbsync"
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: deploy mbsync
  ansible.posix.synchronize:
    src: mbsync
    dest: ~/.config
    delete: yes
    recursive: yes
