- stat:
    path: "~/.config/environment.d"
  register: link

- name: remove symlink
  file:
    path: "~/.config/environment.d"
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: deploy env
  ansible.posix.synchronize:
    src: environment.d
    dest: ~/.config
    delete: yes
    recursive: yes
