- name: Install neovim packages
  become: true
  package:
    name:
      - jq
      - ctags
      - deno
      - fortune-mod
      - gcc
      - global
      - neovim
      - nodejs
      - npm
      - python-neovim
      - python-pygments
- name: deploy neovim
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: ~/.config
    delete: yes
    recursive: yes
  with_items:
    - nvim
    - gtags
- name: Copy environment files to ~/.config/environment.d
  copy:
    src: "environment.d/{{ item }}"
    dest: "~/.config/environment.d/{{ item }}"
  with_items:
    - 60-gtags.conf
- name: Initilize neovim configuration
  shell: |
    nvim --headless -c qa
    nvim --headless -c "call coc#rpc#request('installExtensions', g:coc_global_extensions)" -c qa
    nvim --headless +TSUpdateSync +CocUpdateSync -c qa
  args:
    creates: "~/.config/coc"
