- stat:
    path: "~/.config/nvim"
  register: link

- name: remove symlink
  file:
    path: "~/.config/nvim"
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: deploy neovim
  ansible.posix.synchronize:
    src: nvim
    dest: ~/.config
    delete: yes
    recursive: yes
